using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

// Problem 2
//
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


namespace _002
{
    class Program
    {
        static double[] lookup = new double[101];

        static void Main(string[] args)
        {

            for (int i = 0; i < lookup.Length; i++ )
            {
                lookup[i] = 0;
            }

            int x = 0;
            double sum = 0;

            bool continuea = true;

            while (continuea)
            {
                double nextFib = fib(x);
                if (nextFib > 4000000)
                    continuea = false;
                if (nextFib % 2 == 0)
                    sum += nextFib;
                x++;
            }

            Console.WriteLine(sum);
        }

        static double fib(int x)
        {
            if (x == 0)
                return 0;
            else if (x == 1)
                return 1;
            else
            {
                return calculateFib(x - 1) + calculateFib(x - 2);
            }
        }

        static double calculateFib(int x)
        {
            if (lookup[x] == 0)
                lookup[x] = fib(x);
            return lookup[x];
        }
    }
}
